### ISSUE TITLE
id ad bigint

### ISSUE THREAD

**Issue by keyurshah** [ohmybrew/Basic-Shopify-API#1]
Thanks for the awesome API!

I was using it to download products, and I noticed that it is converting the id to float.  

It seems that Shopify is using bigint for id's

https://twitter.com/tobi/status/294449853319233536

But json_decode turns that to float.

http://php.net/manual/en/function.json-decode.php

> Bitmask of JSON decode options. Currently there are two supported options. The first is JSON_BIGINT_AS_STRING that allows casting big integers to string instead of floats which is the default. The second option is JSON_OBJECT_AS_ARRAY that has the same effect as setting assoc to TRUE.

One solution is to json_decode as:

`$array = json_decode($json, true, 512, JSON_BIGINT_AS_STRING)`

Not sure if that would affect anything else.

Thanks!

**Comment by ohmybrew** [comment]
Hey Sorry for late getting back... no notifications for some reason... will look into this asap, thanks!

**Comment by keyurshah** [comment]
No problem. I moved to a 64 bit version of Php and it seemed to solve the issue without needing to alter code. But maybe a check on the php type would be good

**Comment by ohmybrew** [comment]
Thanks, closed in v1.0.0. Theres some breaking-changes with it to be aware if you're still using the library.

1. PHP 7 is required
2. Namespace is now OhMyBrew
3. getAccessToken is now requestAccessToken

Thanks, closing!
