### ISSUE TITLE
GraphQL Examples

### ISSUE THREAD

**Issue by KimKJDesigns** [ohmybrew/Basic-Shopify-API#10]
Thank you for the GraphQL update a few months back. I've actually had some time to play around with this, as it's my first experience with GraphQL. In a previous issue, you gave an example to pull some basic data, which works perfectly.

Can we get just a few more basic examples using mutations for example? I'm struggling to get one simple query working with Basic-Shopify-API throwing an error at me, ```Undefined property: stdClass::$extensions```.

Any help is much appreciated.

**Comment by ohmybrew** [comment]
Whats the query? Sorry I don't use the GraphQL as its still "beta" by shopify.

**Comment by KimKJDesigns** [comment]
Ok so long story short, can't get mutations working using application/graphql, only application/json.

So lets take the adding of a collection using mutations. [Shopify URL](https://help.shopify.com/en/api/graphql-admin-api/reference/mutation/collectioncreate). 

Using postman, I'm able to use the following, under `content-type: application/json`. This will successfully create a collection and return the approprate results. Note: Postman doesn't play nicely with GraphQL.
```
{
    "query": "mutation collectionCreate($input: CollectionInput!) { collectionCreate(input: $input) { userErrors { field message } collection { id } } }",
    "variables": {
        "input":{
            "title":"Test Collection"
        }
    }
}
```

In Basic-Shopify-API, using that same query will throw an exception. This is because there is no check if the body contains an error, it just assumes there will always be a cost. `$calls = $body->extensions->cost;`. However, changing the `'Content-Type'` to `application/json` allows mutations to work as expected (if you follow the right formula).

I followed this up on the Shopify Slack, to quote from Richard Borek on the GraphQL channel
> Yes I too struggled at first, the key is that GraphQL is only JSON and that the query is a single JSON object.  I was able to reverse engineer this using Insomnia to test then looked at the raw HTTP Requests.  I’m an avid Postman user so if that is the tool your using to test I will say it is possible but not until you grasp the subtle formatting of the JSON object.  Also the request header is application/json not application/graphql.

I know that the Shopify docs state the `content-type` should be `graphql` but I for the life of me cannot get it working.

**Comment by ohmybrew** [comment]
That's interesting... Yes I completely based it off the docs but if it's
just doing JSON then that certainly changes some things. I guess that's why
it's beta :/ This information is great, thank you.

I'll have to mod the code to support this and patch a fix in. Hopefully
this evening if I don't run into issues. And hopefully they do not change
it up in the future to cause a break!

**Comment by ohmybrew** [comment]
@KimKJDesigns  Dug into it... yes using JSON encoded body/header works now.

Passing query (and variables if needed), seems to solve it. Running the below:

```php
<?php
require __DIR__.'/vendor/autoload.php';

use OhMyBrew\BasicShopifyAPI;

$api = new BasicShopifyAPI(true);
$api->setShop('xxx');
$api->setApiKey('xxxx');
$api->setApiPassword('xxx');

$result = $api->graph(
    'mutation collectionCreate($input: CollectionInput!) { collectionCreate(input: $input) { userErrors { field message } collection { id } } }',
    ['input' => ['title' => 'Test Collection']]
);
print_r($result->body->collectionCreate);

$result = $api->graph('{ shop { products(first: 1) { edges { node { handle } } } } }');
print_r($result->body);
```

Produces:

```conf
stdClass Object
(
    [userErrors] => Array
        (
        )
    [collection] => stdClass Object
        (
            [id] => gid://shopify/Collection/63168315434
        )
)

stdClass Object
(
    [shop] => stdClass Object
        (
            [products] => stdClass Object
                (
                    [edges] => Array
                        (
                            [0] => stdClass Object
                                (
                                    [node] => stdClass Object
                                        (
                                            [handle] => test-product
                                        )
                                )
                        )
                )
        )
)
```

Theres a minor bug I need to solve but so far -- working.. will push up a fix within the weekend.

**Comment by ohmybrew** [comment]
@KimKJDesigns Updated with unit tests, passed. Updated readme with examples. Added support for the mutations/variables, a long with checking if costs come into play, and errors.

Would you mind pulling graph-ql-adjustment branch and testing? I've tried product mutations, queries, collection mutations, queries... all seems fine unless I'm missing something.

**Comment by KimKJDesigns** [comment]
@ohmybrew Perfect!! After testing the branch, Basic-Shopify-API is working as expected.  **You've gone above and beyond, integrating it directly into graph function.**

Previously, I was creating a payload (query and variables) and json_encoding the payload before sending the request.

The response checking for errors has stopped the exception being thrown if an error is returned.

```
$query = 'mutation collectionCreate($input: CollectionInput!) { 
    collectionCreate(input: $input) { 
        userErrors { 
            field
            message 
        } 
        collection { 
            id 
        } 
    } 
}';

$variables = [
    'input' => [
        'title' => 'Test Collection'
    ]
];

$shop = $api->graph($query, $variables);
```

Thanks for taking the time to make these changes.

**Comment by ohmybrew** [comment]
Thanks for confirming! Will close this, v3.0.2 (previous v3.0.1) contains the branch fixes, plus passing tests.
