### ISSUE TITLE
Throttling

### ISSUE THREAD

**Issue by keyurshah** [ohmybrew/Basic-Shopify-API#12]
thanks for the wonderful library!

Wondering how you are handling throttling. Are you doing that in your controllers? It's not built into the library, correct?

Thanks.

**Comment by keyurshah** [comment]
ok, thanks. i currently have a intermediary class that handles the throttling and makes different calls to this library but just wanted to make sure that's the best way. have a great weekend!

**Comment by ohmybrew** [comment]
Yup. I thought about including one but I wanted this package to remainin
light weight and allow someone to plug their own methods in. Have a good
one too!

**Comment by keyurshah** [comment]
thanks so much for adding rate limiting!
