### ISSUE TITLE
error on checkouts.json

### ISSUE THREAD

**Issue by hakimihamdan88** [ohmybrew/Basic-Shopify-API#13]
![screen shot 2018-09-14 at 12 41 50 pm](https://user-images.githubusercontent.com/1689992/45530131-baa7ff80-b81b-11e8-87e0-1418cc8b131a.png)

![screen shot 2018-09-14 at 12 44 21 pm](https://user-images.githubusercontent.com/1689992/45530177-f17e1580-b81b-11e8-802b-8b8c0566d522.png)

it seems /admin/checkouts.json does not return http_x_shopify_shop_api_call_limit header

**Comment by hakimihamdan88** [comment]
@ohmybrew

**Comment by ohmybrew** [comment]
Thank you. v3.0.3 pushed with patch.
