### ISSUE TITLE
GraphQL Mutations

### ISSUE THREAD

**Issue by erwantx** [ohmybrew/Basic-Shopify-API#15]
Hello.
The example you provided on how to create mutations (collectionCreate) works without any issues. The problem is I can't get the mutation publishablePublish to work. I'm trying the following:
`$result = $this->GetGraphQLAccess()->graph(
                'mutation publishablePublish($id: ID!, $input: [PublicationInput!]!) {
                        publishablePublish(id: $id, input: $input) {
                            publishable {
                                availablePublicationCount
                                publicationCount
                                publishedOnPublication(publicationId: ' . $channelid . ')
                            }
                            userErrors {
                                field
                                message
                            }                          
                        }
                       }
            ', ['id' => $productid, 'input' => ['publicationId' => $channelid]])`

For some reason, when I print the response, it returns an empty request, like this:

`  ["body"]=>
  object(stdClass)#20 (1) {
    ["publishablePublish"]=>
    NULL
  }
  ["errors"]=>
  bool(true)`

Writing the same query in the Shopify GraphiQL App does actually work. I'm doing this query to publish all products in all available channels. Thanks in advance.

**Comment by ohmybrew** [comment]
There's not enough documentation on the graph for me to support it. While your query does not work, two other types of mutations (basic) I've tried seem to work fine. So in this case I. Not sure, the response is saying there's an error but doesn't seem to indicate what. I'll do a little more digging but ultimately it may lead no where.

**Comment by ohmybrew** [comment]
Whats the response you get inside Shopify's GraphQL tester?

**Comment by erwantx** [comment]
I use the following query:

```
mutation publishablePublish($id: ID!, $input: [PublicationInput!]!) {
  publishablePublish(id: $id, input: $input) {
    userErrors {
      field
      message
    }
    publishable {
      availablePublicationCount
      publicationCount
      publishedOnPublication(publicationId: "Z2lkOi8vc2hvcGlmeS9QdWJsaWNhdGlvbi80MDM2OTg0ODY4")
    }
    shop {
      id
    }
  }
}
```

As for the variables:

```
{
  "id": "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0Lzk5MTgwNDA2Mzc4MA==",
  "input": 
    {"publicationId": "Z2lkOi8vc2hvcGlmeS9QdWJsaWNhdGlvbi80MDM2OTg0ODY4"}
}
```

And I get this response:

```
{
  "data": {
    "publishablePublish": {
      "userErrors": [],
      "publishable": {
        "availablePublicationCount": 4,
        "publicationCount": 5,
        "publishedOnPublication": true
      },
      "shop": {
        "id": "gid://shopify/Shop/ID"
      }
    }
  },
  "extensions": {
    "cost": {
      "requestedQueryCost": 12,
      "actualQueryCost": 12,
      "throttleStatus": {
        "maximumAvailable": 1000,
        "currentlyAvailable": 988,
        "restoreRate": 50
      }
    }
  }
}
```

**Comment by ohmybrew** [comment]
Thanks I'll try and look into this.

**Comment by erwantx** [comment]
Thanks! That did it for me. Everything is working now.
