### ISSUE TITLE
Rest & Graph return type incorrect in docblock

### ISSUE THREAD

**Issue by jaffacake** [ohmybrew/Basic-Shopify-API#20]
Hey, I noticed that in the documentation & in the code that you return an object back from the `rest()` & `graph()` functions. However, your docblock states that it returns an array instead.

This is breaking my coding standards checks and I've had to add in another casting into my code.

Could you update the docblock return type?

Thanks!

**Comment by ohmybrew** [comment]
Ah.. originally it was an array and was changed a few versions back. I will update.

**Comment by jaffacake** [comment]
I've pushed up a pull request for you 👍
