### ISSUE TITLE
GraphQL call does not work properly

### ISSUE THREAD

**Issue by salvobunetto** [ohmybrew/Basic-Shopify-API#22]
Using the sample code
 `$call = $api->graph('{ shop { products(first:1) { edges { node { handle, id } } } } }');`
You receive the response

Instead if you use
`$call = $api->graph('{ shop { products(last:1) { edges { node { handle, id } } } } }');`
I receive nothing

Even if I try to make a query
`$call = $api->graph('{ shop { products(query:"tag:foo") { edges { node { handle, id } } } } }');`
I receive nothing

**Comment by ohmybrew** [comment]
I am getting results. what is your response code and body.

**Comment by salvobunetto** [comment]
[first1.txt](https://github.com/ohmybrew/Basic-Shopify-API/files/3146568/first1.txt)
[last1.txt](https://github.com/ohmybrew/Basic-Shopify-API/files/3146569/last1.txt)
[query.txt](https://github.com/ohmybrew/Basic-Shopify-API/files/3146570/query.txt)

**Comment by ohmybrew** [comment]
For your second call:

> [message] => using last without before is not supported

For your last call (query):

> [message] => you must provide one of first or last

**Comment by salvobunetto** [comment]
I wondered why it did not work, I'm just approaching GraphQL and I did not realize that you had to specify the quantity, thanks for your patience and the library.
