### ISSUE TITLE
GET /admin/oauth/access_scopes.json - 404 ERROR

### ISSUE THREAD

**Issue by navneet29** [ohmybrew/Basic-Shopify-API#24]
```
Array
(
    [errors] => [API] Invalid API key or access token (unrecognized login or wrong password)
    [status] => 401
)
```
Even when Token is correct. Same api call works with same token in postman.

At first i realised that, `**Basic-Shopify-API**` is adding version to this endpoint, while this endpoint do not support versioning. 
I created a PR to fix this, Please check.

Now, **404 error** is fixed but instead i am getting **401** error. Which is very weird.

**Comment by ohmybrew** [comment]
Released!

**Comment by navneet29** [comment]
Hi @ohmybrew 
Problem is still there, this PR will fix 404 error, but still we get 401 Unauthorized error.
Here is the code i am using
```
$api = new BasicShopifyAPI();
$api->setVersion('2019-04');
$api->setShop($_SESSION['shop']);
$api->setAccessToken($_SESSION['oauth_token']);
$result = $api->rest('GET','/admin/oauth/access_scopes.json');
print_r($result);
```
oauth_token and shop is correct ( tried in postman, it works )
Also, all other API calls except `/admin/oauth/access_scopes.json` one, works perfectly.

**Comment by ohmybrew** [comment]
Just pushed up a fix for this.
