### ISSUE TITLE
Newly created shops do not allow GET params to be sent as JSON.

### ISSUE THREAD

**Issue by ncpope** [ohmybrew/Basic-Shopify-API#3]
Shops that are newly created no longer use JSON GET parameters. Requests result in a 400 error.

I am not sure which shops are affected but my older demo store from 2014 is unaffected and all demo stores created under the affiliate program after December, 1st 2017 have been affected in my experience.

The solution to this issue is to check if a request is GET and then to place the parameters on the url.

error example:

`$request = $api->request('GET', '/admin/products.json', ['page' => $page, 'limit' => $limit]);`

![laravel-shopify-error](https://user-images.githubusercontent.com/1903724/33783197-97d82864-dc10-11e7-93bd-2ba44879a881.jpg)

solution example:

`$request = $api->request('GET', '/admin/products.json?page=' . $page . '&limit=' . $limit);`

![laravel-shopify-solution](https://user-images.githubusercontent.com/1903724/33783193-94620484-dc10-11e7-9f71-91bd32bfc208.jpg)

**Comment by ncpope** [comment]
I tried to create a pull request with a fix but the CI failed. Here is my submission if anyone wants to give it a shot: https://github.com/ohmybrew/Basic-Shopify-API/pull/4/commits/731828ee39dba91052c0c91da8a712fe5386ae2e

**Comment by ohmybrew** [comment]
Okay, I tested a store from a few years ago... works.
Tested a store created passed July... works.
Created a store for today (Dec 18th)... fails.

So yeah, seems Shopify made a API change in the backend... hmm... wish they versioned the API.

I will muster up a fix and produce some tests to counter this. Thanks for the note on this @ncpope . I should have a fix out by tonight.

**Comment by ohmybrew** [comment]
@ncpope This should now be solved with v1.0.1 now

**Comment by ohmybrew** [comment]
Upon furthur testing of different stores created at a range of times, all seems to be good now, I'll close this.
