### ISSUE TITLE
Feature request - retry n times with backoff rate settings for api failures

### ISSUE THREAD

**Issue by Zelfapp** [ohmybrew/Basic-Shopify-API#30]
Great library! I'd like to make a feature request for a retry option.

* ```$api->setIntervalSeconds(n)```
  * Defaults to 1
  * Where n is a positive integer representing seconds between retries

* ```$api->setMaxAttempts(n)```
  * Defaults to 2
  * Where n is the number of times to retry a failed API call before throwing an exception.

* ```$api->setBackOffRate(n)```
  * Default to 2 seconds.
  * Where n is the positive integer representing the multiplier by which the retry interval increases during each attempt.

AWS does this, e.g., with Step Functions: https://docs.aws.amazon.com/step-functions/latest/dg/concepts-error-handling.html

**Comment by ohmybrew** [comment]
Hi there! it's a good idea and achievable with Guzzle itself. But at this time I won't be adding this. I'll keep this on my notes though to work through :)
