### ISSUE TITLE
GraphQL Rate Limitting

### ISSUE THREAD

**Issue by uttamrabadiya** [ohmybrew/Basic-Shopify-API#31]
I am using this package with a month,
I found a little bit missing functionality for GraphQL of **Rate Limitting**.
As you have covered `RateLimiting` for `REST API`, and it works without throwing any error.
I was trying to implement it for my GraphQL calls, but it's not that easy as i have thought, can you please implement **Rate Limitting** for GraphQL? It will be real great update.

I am trying to implement this functionality on myself.  I will need current **Query Cost** and **Available Cost** to add sleep time before making GraphQL request, but I am not able to calculate my current **Query Cost**, I can retrieve **Available Cost** from `apiCallLimits`, if we can calculate **query cost** before making request than might we can implement **Rate Limitting** functionality for GraphQL.

**Comment by ohmybrew** [comment]
GraphQL has a cost not a limit. So you would need to detect this on your own by seeing how much is left.

**Comment by uttamrabadiya** [comment]
Yeah, I am trying to calculate **query cost** before performing any query. But I still don't understand how they are calculating this **query cost** based on **query**

**Comment by ohmybrew** [comment]
Ah.

> Shopify calculates the cost of a query both before and after query execution. The requested cost is based on the number of fields requested. The actual cost is based on the results returned, since the query can end early due to an object type field returning null, or connection fields can return fewer edges than requested.

> Design your app with API rate limits in mind to best handle request limits and avoid errors. To avoid rate limiting:
> 1. Vary time intervals of requests to avoid sending traffic in spikes.
> 2. Avoid requesting overlapping data.
> 3. Use the query response to balance your requests.


> To get a detailed breakdown of how each field contributes to the requested cost, you can include the header 'X-GraphQL-Cost-Include-Fields': true in your request.

**Comment by uttamrabadiya** [comment]
Hey,
I found a way to calculate **query cost**, Can you help me to improve this?

**Comment by ohmybrew** [comment]
Definately a good break down. I can keep a sticky to your comment for others who are wondering. I won't internally implement it though, it would be too much maintenance on my side if things change inside Shopify.

**Comment by uttamrabadiya** [comment]
Great, can you help me to test this method further? I mean if you have some complex query samples which i can perform to calculate my solution. I can know more if it works in every situation or not. For now, i have tested in some simple queries only.

**Comment by ohmybrew** [comment]
Sorry I do not. Maybe check Shopify docs? they have a nice few samples you could test on.
