### ISSUE TITLE
Delete request params are being ignored

### ISSUE THREAD

**Issue by nmrdxt** [ohmybrew/Basic-Shopify-API#32]
Hello!

Not very familiar with git :/ but would like to report that delete request's params are being ignored.

I believe line 718 in the api should something along the lines of:

$guzzleParams[strtoupper($type) === 'GET' || strtoupper($type) === 'DELETE' ? 'query' : 'json'] = $params;

originally its 

$guzzleParams[strtoupper($type) === 'GET' ? 'query' : 'json'] = $params;

Thank you for an awesome solution!

**Comment by ohmybrew** [comment]
What type of request are you sending?

**Comment by nmrdxt** [comment]
Delete request to assets.json endpoint

https://help.shopify.com/en/api/reference/online-store/asset#destroy-2019-07

**Comment by ohmybrew** [comment]
Hmm mind showing me the code you're using?

**Comment by nmrdxt** [comment]
Sure, here it is:

```
        $url = "/admin/themes/{$selectedTheme}/assets.json";

        $params = [
            'asset[key]' => $assetKey
        ];

        $asset = $this->api()->rest('DELETE', $url, $params);
```

Thanks!

**Comment by ohmybrew** [comment]
It needs to be formed as a proper array.

Try:

```php
        $url = "/admin/themes/{$selectedTheme}/assets.json";

        $params = [
            'asset' => ['key' => $assetKey],
        ];

        $asset = $this->api()->rest('DELETE', $url, $params);
```

**Comment by nmrdxt** [comment]
Roger that - will give it a go and report back. Cheers!

**Comment by ohmybrew** [comment]
Let me know, if that doesn't work i'll mod the code but I was sure it accepted vars posted as json.

**Comment by ohmybrew** [comment]
@nmrdxt How did you make out?
