### ISSUE TITLE
Include Shopify New Muti Currencies Support in API request

### ISSUE THREAD

**Issue by jasontxf** [ohmybrew/Basic-Shopify-API#33]
Hello, thank you for creating this wonderful API!
I'm just wondering if there is a way to include

```
'X-Shopify-Api-Features': 'include-presentment-prices'
```

in the header when calling rest()?

**Comment by ohmybrew** [comment]
I'll add a headers() function to inject headers.

**Comment by jasontxf** [comment]
That would be great! Thank you for actively maintaining these repo!

**Comment by ohmybrew** [comment]
v5.5.0 is out and solves this.

New API is: `$api->rest(string $type, string $path, array $params = null, array $headers = []);`

So example:

`$api->rest('GET', '/admin/orders.json', null, ['X-Shopify-Api-Features' => 'include-presentment-prices']);`

Thank you!
