### ISSUE TITLE
Restricting DB data to only the connected shop/user

### ISSUE THREAD

**Issue by polibou** [ohmybrew/Basic-Shopify-API#35]
I'm a Laravel newbie and maybe I missed it somewhere here, but how is everyone managing queries for each shop so that they only have access to their own data?  Currently I'm passing a shop ID condition in to all my queries.  Is there something built in that passes the shop ID or other authenticated ID to the model?

General search is suggesting that I extend the model to include the shop ID so I don't have to added it to every query.  I'm still trying to figure out how to do this.  However it seems like a package that is designed to handle multiple shops would have this already, so I think I'm missing something.

**Comment by ohmybrew** [comment]
I think you meant to put this into laravel-shopify, my other repo?

Either way, yes, the currently shop is authenticated and stored in session.
The shop info is then pulled from the database (shopify_token).
The token is used in the requests outbound which is the correct shop.

**Comment by polibou** [comment]
Sorry, yes I did mean to post it in the other repo.  I'll continue the discussion over there.
