### ISSUE TITLE
Webhook in Private App

### ISSUE THREAD

**Issue by veed76** [ohmybrew/Basic-Shopify-API#37]
Hi @ohmybrew 

I used this package for a Private App.
So, how can I use the webhook in a private app? It will auto verify the webhook call or I have to verify manually?

**Comment by ohmybrew** [comment]
"Private" API calls, as in the ones where you manually create an API key in the merchant's store, to my knowledge, you can not create webhooks for this.

You would need to create a semi-private app, where its a "public" app, just not listed on the app store. This way, you have an app api key which can then add webhooks.
