### ISSUE TITLE
New pagination headers as of 2019-07

### ISSUE THREAD

**Issue by robcurry** [ohmybrew/Basic-Shopify-API#39]
Would it be possible to support the new cursor based pagination recently added to the REST API version 2019-07?

As details here:
https://help.shopify.com/en/api/guides/paginated-rest-results

**Comment by ohmybrew** [comment]
Not sure there's anything I need to do? This library allows you to make the calls and grab the headers.

**Comment by mandeepsandhu91** [comment]
How can I grab the headers from a call

**Comment by ohmybrew** [comment]
The library returns a full Guzzle response, so you could do this:

```php
$call = 
$api->rest('GET', '/admin/shop.json');

$result = $call->body->shop; // Now has shop info
$header = $call->response->getHeader('link');
```

**Comment by ohmybrew** [comment]
Actually... I may implement this internally to return "->link" value.

**Comment by ohmybrew** [comment]
6.1.0 has this now.
