### ISSUE TITLE
Serialization of 'Closure' is not allowed in laravel job queue.

### ISSUE THREAD

**Issue by sunny047** [ohmybrew/Basic-Shopify-API#40]
Hi, i have created a job to handle large product data. I have using laraveljob queue to handle product data but i am getting "Serialization of 'Closure' is not allowed " error due to to client configuration i.e $api =  new BasicShopifyAPI();  . 

I know we need to serialize this $api =  new BasicShopifyAPI();  but i don't know how i can do this.
Laravel queue job class not allow this configuration. Can you please help me ,how we can handle this in the laravel job queue ?

**Comment by ohmybrew** [comment]
You can not init anything like that in your laravel job constructors, it attempts to serialize it. Google around for "Laravel job serialization issue" and you'll see why.
