### ISSUE TITLE
REST call doesn't add version number.

### ISSUE THREAD

**Issue by abishekrsrikaanth** [ohmybrew/Basic-Shopify-API#42]
Based on the docs to create the Fulfillment [here](https://help.shopify.com/en/api/reference/shipping-and-fulfillment/fulfillment?api[version]=2019-07#create-2019-07), I used the following code using this package.

```
$api = new BasicShopifyAPI();
$api->setVersion('2019-07'); // "YYYY-MM" or "unstable"
$api->setShop('your shop here');
$api->setAccessToken('your token here');

// Now run your requests...
$data = [
     'fulfillment'=>[
         //  ....
     ]
];
$api->rest('POST','/admin/api/orders/'.$orderId.'/fulfillments.json',$data);
```

The above call doesn't seem to add the set version info to the URI before sending the request to Shopify. i had to manually append the version segment to the URI.

**Comment by ohmybrew** [comment]
Its becuase you have the /admin/api. Its assuming you're supplying the version yourself.

Just do `/admin/orders/$orderId/fulfillments.json`

**Comment by abishekrsrikaanth** [comment]
Thanks, appreciate it.
