### ISSUE TITLE
The errors of the shopify gateway is not displayed properly. 

### ISSUE THREAD

**Issue by jackkam85** [ohmybrew/Basic-Shopify-API#50]
After reset api returns, there is no display of the correct error message.
 
$shop=ShopifyApp:shop();
$product = [
                "title" =>'test',
                "vendor" => 'abc',
               
                "options"=>[
							{
							  'name':'color_name'
							},
							{
							  'name':'size_name'
							}
							],
                "images" => [
                    [
                        "src" =>'http://www.google.com/logo.jpg'
                    ]
                    
                ]
            ];
          
          
$result=$shop->api()->rest('POST','/admin/api/2019-07/products.json',['product'=>$product]);
$errors = $result->errors;
echo $errors;

The errors message not show.

if print_r($errors) the will show :

 "message": "Allowed memory size of 2147483648 bytes exhausted (tried to allocate 1071648768 bytes)",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalErrorException",

**Comment by ohmybrew** [comment]
That is the error message. There is no API error judging by this.
