### ISSUE TITLE
Add error key to error response

### ISSUE THREAD

**Issue by diemah77** [ohmybrew/Basic-Shopify-API#56]
Currently you only check for the error key: `$body = property_exists($body, 'errors') ? $body->errors : null;`

I think it definitely makes sense to add a check for the `error` key as well. This is the case e.g. when creating fulfillments with missing data: `"error":"location_id must be specified when creating fulfillments."`

This my workaroud for now: 
```
if ($body !== null) {
    if (property_exists($body, 'errors'))
    {
        $body = $body->errors;
    }
    elseif (property_exists($body, 'error'))
    {
        $body = $body->error;
    }
    else
    {
        $body = null;
    }
}
```

**Comment by ohmybrew** [comment]
Solved. Will be part of next release shortly, just reviewing other tickets.

**Comment by roberttolton** [comment]
Is the new release ready?
