### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by roberttolton** [ohmybrew/Basic-Shopify-API#59]
Just noticed an error in the 'Errors' section of the documentation, that currently states:

```
$call = $api->rest('GET', '/admin/non-existant-route-or-object.json');

if ($call->errors) {
  echo "Oops! {$call->errors->status} error";
  print_r($call->errors->body);

  // Original exception can be accessed via `$call->errors->exception`
  // Example, if response body was `{"error": "Not found"}`...
  /// then: `$call->errors->body->error` would return "Not Found"
}
```

However, `errors` is a boolean and trying to access `$call->errors->exception` results in "Trying to get property 'exception' of non-object"

**Comment by SKUtrang** [comment]
Documentation link not working

https://ohmybrew.com/Basic-Shopify-API

**Comment by tiknajobmak** [comment]
Documentation link not working. Gives 404 error.

https://ohmybrew.com/Basic-Shopify-API

**Comment by ohmybrew** [comment]
Fixed, thanks.
