### ISSUE TITLE
extractLinkHeader fails when underscore is present in page link

### ISSUE THREAD

**Issue by rasmustaarnby** [ohmybrew/Basic-Shopify-API#60]
I got an `invalid value` error from Shopify on page_info. 

Looking into the raw request I can see that the parsed next link does not match the link in the raw request. 

Direct from the link header:
`<https://domain.myshopify.com/admin/api/2019-10/products.json?limit=100&page_info=eyJkaXJlY3Rpb24iOiJwcmV2IiwibGFzdF9pZCI6NDI3NDE1NjQzNzYzOSwibGFzdF92YWx1ZSI6IkJ5IE5vcmQgLSBEZWxsaW5nIGxpbm5lZHVrIC0gMiBzdG9ybGVrYXIgb2NoIDMgZsOkcmdlciJ9>; rel="previous", <https://domain.myshopify.com/admin/api/2019-10/products.json?limit=100&page_info=eyJkaXJlY3Rpb24iOiJuZXh0IiwibGFzdF9pZCI6MjAxMjc3MjA0MDc2NywibGFzdF92YWx1ZSI6IkNobG_DqSAtIExvdmUgU3RvcnkgRURQIDMwIG1sIn0>; rel="next"`

Parsed links:
`"next": "eyJkaXJlY3Rpb24iOiJuZXh0IiwibGFzdF9pZCI6MjAxMjc3MjA0MDc2NywibGFzdF92YWx1ZSI6IkNobG"
"previous": "eyJkaXJlY3Rpb24iOiJwcmV2IiwibGFzdF9pZCI6NDI3NDE1NjQzNzYzOSwibGFzdF92YWx1ZSI6IkJ5IE5vcmQgLSBEZWxsaW5nIGxpbm5lZHVrIC0gMiBzdG9ybGVrYXIgb2NoIDMgZsOkcmdlciJ9"`

The issue seems to be the underscore in the link and can be fixed by adding `_` to the regex. 

`$regex = '/<.*page_info=([a-z0-9\-_]+).*>; rel="?{type}"?/i';`

https://github.com/ohmybrew/Basic-Shopify-API/blob/master/src/OhMyBrew/BasicShopifyAPI.php#L1113

**Comment by ohmybrew** [comment]
Fixed, will patch shortly.
