### ISSUE TITLE
GraphQL Support

### ISSUE THREAD

**Issue by ohmybrew** [ohmybrew/Basic-Shopify-API#7]
Although in beta, I will add support for it.

At a glance, this will involve making an abstract class for the base, with an interface; then, creating a new class for the graphQL which extends the base; then, modifying the original class to extend the base.

The GraphQL functions pretty similar. High level its just a different endpoint, and different limits to grab (costs).

Will be investigating this in a new branch. There should be no breaking changes for this.

**Comment by ohmybrew** [comment]
Branch is now https://github.com/ohmybrew/Basic-Shopify-API/tree/graph-ql

This actually will cause a breaking change since its now under a new namespace... will bump version to major on release.

Code is still being developed.

**Comment by ncpope** [comment]
great news, I was actually just researching this. I wasn't too familiar with graphQL, it sounds great though.

Thanks @ohmybrew  🎉

**Comment by ohmybrew** [comment]
@ncpope Its great, really lets you get the data you need without multiple calls like with their REST API.

It'll be pretty basic (to keep with the library's initial goal). Example:

```php
$api = new GraphAPI();
$api->setShop('example.myshopify.com');
$api->setApiPassword('!@#');

$query =<<<QL
{
    shop {
        products(first: 2) {
            edges {
                node {
                    id
                    handle
                }
            }
        }
    }
}
QL;

$res = $api->request($query);
foreach ($res->shop->products->edges as $data) {
  echo $data->node->handle; // Returns product's handle as per requested in query
}
```

Both the Graph class and Rest class will have the same interface so they can both be used at the same time for projects.

I'll probably have it finalized next week (currently it basically working, just need more tests). Given its marked BETA by Shopify, things may change down the road but I don't foresee it changing enough to affect this feature build.
